vim9script
set nocompatible

set textwidth=80
set formatoptions+=mM
set formatoptions-=t
set nojoinspaces

set autoindent
set tabstop=4
set shiftwidth=0
set expandtab

set relativenumber
set undofile
set encoding=utf-8
set incsearch
set hlsearch
set hidden
set nostartofline
set belloff=all
set viminfo=

set grepprg=rg\ --vimgrep\ -uu

autocmd BufWritePre * :%s/\s\+$//e
