pulse.cmd = [
    {
        cmd = "load-module"
        args = "module-null-sink media.class=Audio/Sink sink_name=Foo channel_map=stereo format=s32le"
    }
    {
        cmd = "load-module"
        args = "module-null-sink media.class=Audio/Sink sink_name=Bar channel_map=stereo format=s32le"
    }
    {
        cmd = "load-module"
        args = "module-null-sink media.class=Audio/Sink sink_name=Buzz channel_map=stereo format=s32le"
    }
]
